name: WordPress Plugin Quality Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1, 8.2, 8.3]

    steps:
      # --------------------------------------------------
      # 1. Checkout
      # --------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Setup PHP
      # --------------------------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      # --------------------------------------------------
      # 3. PHP Syntax Check
      # --------------------------------------------------
      - name: Validate PHP syntax
        run: |
          find . -type f -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      # --------------------------------------------------
      # 4. Install Composer dependencies (LOCAL ONLY)
      # --------------------------------------------------
      - name: Install Composer dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist
          else
            echo "No composer.json found, skipping Composer install."
          fi

      # --------------------------------------------------
      # 5. Verify PHPCS (if installed)
      # --------------------------------------------------
      - name: Verify PHPCS installation
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs -i
          else
            echo "PHPCS not installed, skipping."
          fi

      # --------------------------------------------------
      # 6. Auto-fix PHPCS (safe fixes only)
      # --------------------------------------------------
      - name: Auto-fix PHPCS formatting
        continue-on-error: true
        run: |
          if [ -f vendor/bin/phpcbf ]; then
            vendor/bin/phpcbf \
              --standard=WordPress \
              --extensions=php \
              --ignore=vendor,node_modules,.github \
              .
          else
            echo "PHPCBF not available, skipping."
          fi

      # --------------------------------------------------
      # 7. PHPCS / WPCS
      # --------------------------------------------------
      - name: Run PHPCS (WordPress standards)
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs -v -p \
              --warning-severity=0 \
              --standard=WordPress,WordPress-Extra,WordPress-Docs \
              --extensions=php \
              --ignore=vendor,node_modules,.github \
              .
          else
            echo "PHPCS not available, skipping."
          fi

      # --------------------------------------------------
      # 8. PHPCompatibility
      # --------------------------------------------------
      - name: Run PHPCompatibility
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs \
              --standard=PHPCompatibilityWP \
              --runtime-set testVersion 7.4-8.3 \
              --extensions=php \
              --ignore=vendor,node_modules,.github \
              .
          else
            echo "PHPCompatibility not available, skipping."
          fi

      # --------------------------------------------------
      # 9. PHPUnit (optional)
      # --------------------------------------------------
      - name: Run PHPUnit tests
        run: |
          if [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then
            vendor/bin/phpunit
          else
            echo "No PHPUnit config found, skipping tests."
          fi

      # --------------------------------------------------
      # 10. Node / JS / CSS Lint (optional)
      # --------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping NPM."
          fi

      - name: Run ESLint
        run: |
          if [ -f package.json ]; then
            npx eslint . || true
          fi

      - name: Run Stylelint
        run: |
          if [ -f package.json ]; then
            npx stylelint "**/*.css" || true
          fi

      # --------------------------------------------------
      # 11. readme.txt validation
      # --------------------------------------------------
      - name: Validate readme.txt
        run: |
          if [ -f readme.txt ]; then
            grep -q "=== Description ===" readme.txt || echo "⚠ Missing Description section"
            grep -q "== Changelog ==" readme.txt || echo "⚠ Missing Changelog section"
          else
            echo "No readme.txt found."
          fi

